<?php
use Magento\Framework\View\Element\Template;
?>

<ul>
    <li>Movie 1</li>
    <li>Movie 2</li>
    <li>Movie 3</li>
</ul>

<div data-bind="scope: 'watchingmovies'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
	{
	    "*": {
	        "Magento_Ui/js/core/app": {
                "components": {
                    "watchingmovies": {
                        "component": "NicolasBlancoM_WatchingMovies/js/view/watchingmovies",
                        "template": "NicolasBlancoM_WatchingMovies/watchingmovies",
                        "movies": [
                            {"label": "Movie 1"},
                            {"label": "Movie 2"},
                            {"label": "Movie 3"},
                            {"label": "Movie 4"}
                        ]
                    }
                }
	        }
	    }
	}
</script>